### ISSUE TITLE
x11

### ISSUE THREAD

**Issue by vitalygoji** [cornerpirate/JS2PDFInjector#2]
Is there any way to run it without x server? I tested it on my workstation, it worked well but on server (without x window) it  gives me "Can't connect to X11 window server"

Thank you!

**Comment by cornerpirate** [comment]
A legit problem there.

**Comment by cornerpirate** [comment]
It turned out the tool worked all along but you needed to supply the full path to the PDF and JS files. If you have the files in the same folder just supply "./filename.pdf ./filename.js". When you use the GUI it gets the full path for the files out of the JFileChooser, but if you supply arguments it doesn't have the full path.

You still need to supply the full paths but the README.md has been updated to mention it. 

I have also migrated the source to a Maven based project to make it easier to maintain, and it is now built with an up-to-date version of pdfbox. 

Closing this issue because I have provided a version that works headless. You will still get a headless error if you run without parameters but the error is pretty clear about the lack of X11.
